const ptBR: Record<string, any> = {
  "Flows.builder.canvasView": "Quadro Visual",
  "Flows.builder.listView": "Modo Lista",
  "Flows.builder.addNode": "Adicionar Nó",
  "Flows.editorState.modeAdd": "Adicionar",
  "Flows.editorState.modeRemove": "Remover",
  "Flows.editorState.media": "Mídia",
  "Flows.validate.noIssues": "Sem problemas",
  "Flows.validate.summary": "{errorCount} erros e {warningCount} avisos",
  "Flows.builder.categories.messaging": "MENSAGENS",
  "Flows.builder.categories.logic": "LÓGICA E DADOS",
  "Flows.builder.categories.flow": "CONTROLE DE FLUXO",
  "Flows.builder.nodes.start.label": "Início",
  "Flows.builder.nodes.start.blurb": "Ponto de entrada",
  "Flows.builder.nodes.send_message.label": "Mensagem",
  "Flows.builder.nodes.send_message.blurb": "Enviar texto simples",
  "Flows.builder.nodes.send_buttons.label": "Botões",
  "Flows.builder.nodes.send_buttons.blurb": "Enviar texto com botões interativos",
  "Flows.builder.nodes.send_list.label": "Menu Lista",
  "Flows.builder.nodes.send_list.blurb": "Menu de opções (até 10 itens)",
  "Flows.builder.nodes.send_media.label": "Mídia",
  "Flows.builder.nodes.send_media.blurb": "Imagem, vídeo, áudio ou PDF",
  "Flows.builder.nodes.collect_input.label": "Entrada",
  "Flows.builder.nodes.collect_input.blurb": "Aguardar texto do cliente",
  "Flows.builder.nodes.condition.label": "Condição",
  "Flows.builder.nodes.condition.blurb": "Decidir baseado em variável",
  "Flows.builder.nodes.set_tag.label": "Tag",
  "Flows.builder.nodes.set_tag.blurb": "Adicionar ou remover tag",
  "Flows.builder.nodes.handoff.label": "Atendente",
  "Flows.builder.nodes.handoff.blurb": "Passar para atendimento humano",
  "Flows.builder.nodes.end.label": "Fim",
  "Flows.builder.nodes.end.blurb": "Encerrar o fluxo",
  "Flows.builder.noNodesYet": "Nenhum nó adicionado ainda",
  "Flows.builder.nodesTitle": "{count} nó(s)",
  "Flows.builder.keywordsPlaceholder": "Ex: ajuda, suporte, comprar",
  "Flows.builder.triggerTitle": "Gatilho de Início",
  "Flows.builder.whenLabel": "Quando este fluxo inicia?",
  "Flows.builder.triggerKeywordTitle": "Palavras-chave",
  "Flows.builder.triggerFirstInboundTitle": "Primeira mensagem",
  "Flows.builder.triggerManualTitle": "Manual (via API/Automação)",
  "Flows.builder.keywordsLabel": "Palavras-chave",
  "Flows.builder.entryNodeTitle": "Nó de entrada",
  "Flows.builder.entryNodePlaceholder": "Selecione por onde o fluxo começa",
  "Flows.builder.badgeEntry": "ENTRADA",
  "Flows.builder.setAsEntry": "Definir como entrada",
  "Flows.builder.removeNode": "Remover nó",
  "Flows.builder.deleteNode": "Excluir nó",
  "Flows.builder.hideAdvanced": "Ocultar avançado",
  "Flows.builder.showAdvanced": "Mostrar avançado",
  "Flows.builder.nodeKeyLabel": "Chave do nó",
  "Flows.builder.replyIdsHint": "Apenas use IDs caso saiba o que está fazendo",
  "Flows.builder.end": "Fim do fluxo",
  "Flows.builder.saved": "Fluxo salvo!",
  "Flows.builder.statusActivated": "Fluxo ativado!",
  "Flows.builder.statusArchived": "Fluxo arquivado",
  "Flows.builder.statusDraft": "Fluxo salvo como rascunho",
  "Flows.builder.none": "Nenhum",
  "Flows.builder.advancesTo": "Avança para",
  "Flows.builder.textToCustomer": "Texto da mensagem",
  "Flows.builder.promptToCustomer": "Texto da pergunta",
  "Flows.builder.varKeyLabel": "Nome da variável",
  "Flows.builder.varKeyPlaceholder": "ex: nome_cliente",
  "Flows.builder.varKeyHelp": "Esta variável será salva com a resposta.",
  "Flows.builder.advanceAfterCapture": "Avançar após responder",
  "Flows.builder.internalNote": "Nota interna",
  "Flows.builder.endNodeHelp": "Fim do fluxo. O usuário sairá da automação.",
  "Flows.builder.bodyText": "Texto principal",
  "Flows.builder.footerText": "Rodapé",
  "Flows.builder.buttonsHelp": "Máx. 3 botões.",
  "Flows.builder.optionTitlePlaceholder": "Ex: Falar com atendente",
  "Flows.builder.nextNodePlaceholder": "Próximo nó",
  "Flows.builder.addButton": "Adicionar botão",
  "Flows.builder.buttonLabel": "Texto do botão",
  "Flows.builder.rowsHelp": "Você pode ter até 10 opções no total.",
  "Flows.builder.sectionTitlePlaceholder": "Seção {count}",
  "Flows.builder.rowTitlePlaceholder": "Título da opção",
  "Flows.builder.addRow": "Adicionar opção",
  "Flows.builder.addSection": "Adicionar seção",
  "Flows.builder.ifLabel": "Se o contato...",
  "Flows.builder.capturedVariable": "Tiver variável",
  "Flows.builder.contactHasTag": "Tiver a tag",
  "Flows.builder.contactField": "Campo do contato",
  "Flows.builder.varName": "Variável",
  "Flows.builder.tagLabel": "Tag",
  "Flows.builder.fieldLabel": "Campo",
  "Flows.builder.pickField": "Escolher",
  "Flows.builder.tagUuidPlaceholder": "Ex: tag-123",
  "Flows.builder.operatorLabel": "Condição",
  "Flows.builder.isPresent": "Existe",
  "Flows.builder.isAbsent": "Não existe",
  "Flows.builder.equals": "É igual a",
  "Flows.builder.contains": "Contém",
  "Flows.builder.valueLabel": "Valor",
  "Flows.builder.ifTrueAdvance": "Se Verdadeiro avança para",
  "Flows.builder.ifFalseAdvance": "Se Falso avança para",
  "Flows.builder.actionLabel": "Ação",
  "Flows.builder.addTag": "Adicionar Tag",
  "Flows.builder.removeTag": "Remover Tag",
  "Flows.builder.thenAdvanceTo": "E depois avançar para",
  "Flows.builder.mediaTypeLabel": "Tipo de mídia",
  "Flows.builder.imageLabel": "Imagem",
  "Flows.builder.videoLabel": "Vídeo",
  "Flows.builder.documentLabel": "Documento",
  "Flows.builder.fileLabel": "Arquivo",
  "Flows.builder.removeFile": "Remover",
  "Flows.builder.uploading": "Enviando...",
  "Flows.builder.clickToUpload": "Clique para enviar",
  "Flows.builder.captionLabel": "Legenda",
  "Flows.builder.filenameLabel": "Nome do arquivo",
  "Flows.builder.filenamePlaceholder": "ex: boleto.pdf",
  "Flows.builder.advanceAfterSending": "Avançar após enviar",
  "Flows.builder.options": "{count} opções",
  "Flows.builder.optionsAcrossSections": "{rowCount} opções em {sectionCount} seções",
  "Flows.builder.media": "Mídia",
  "Flows.builder.noFile": "Sem arquivo",
  "Flows.builder.hasTag": "tem a tag {tag}",
  "Flows.builder.opContains": "contém",
  "Flows.builder.opExists": "existe",
  "Flows.builder.opMissing": "não existe",
  "Flows.builder.modeRemove": "Remover",
  "Flows.builder.modeAdd": "Adicionar",
  "Flows.builder.tagPicked": "{mode} a tag {tag}",
  "Flows.builder.tagNone": "{mode} tag (nenhuma)",
  "Flows.validate.jumpToNode": "Ir para {key}",
};


export function useTranslations(namespace?: string) {
  const t = (key: string, values?: Record<string, any>) => {
    const fullKey = namespace ? `${namespace}.${key}` : key;
    let text = ptBR[fullKey];
    
    if (!text) {
      const parts = key.split('.');
      text = parts[parts.length - 1];
    }

    if (values && text) {
      for (const [k, v] of Object.entries(values)) {
        text = text.replace('{'+k+'}', String(v));
      }
    }
    return text || key;
  };
  t.rich = (key: string, values?: Record<string, any>) => {
    return t(key, values);
  };
  return t;
}
