/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBroadcastsRouteImport } from './routes/_app.broadcasts'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppConectarRouteImport } from './routes/_app.conectar'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppDisparosRouteImport } from './routes/_app.disparos'
import { Route as AppFluxosRouteImport } from './routes/_app.fluxos'
import { Route as AppGruposRouteImport } from './routes/_app.grupos'
import { Route as AppRespostasRouteImport } from './routes/_app.respostas'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppFluxosFlowIdRouteImport } from './routes/_app.fluxos.$flowId'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsRoute = AppBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppConectarRoute = AppConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppDisparosRoute = AppDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxosRoute = AppFluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposRoute = AppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppRespostasRoute = AppRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxosFlowIdRoute = AppFluxosFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => AppFluxosRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/chat': typeof AppChatRoute
  '/conectar': typeof AppConectarRoute
  '/config': typeof AppConfigRoute
  '/contatos': typeof AppContatosRoute
  '/disparos': typeof AppDisparosRoute
  '/fluxos': typeof AppFluxosRouteWithChildren
  '/grupos': typeof AppGruposRoute
  '/respostas': typeof AppRespostasRoute
  '/templates': typeof AppTemplatesRoute
  '/fluxos/$flowId': typeof AppFluxosFlowIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/chat': typeof AppChatRoute
  '/conectar': typeof AppConectarRoute
  '/config': typeof AppConfigRoute
  '/contatos': typeof AppContatosRoute
  '/disparos': typeof AppDisparosRoute
  '/fluxos': typeof AppFluxosRouteWithChildren
  '/grupos': typeof AppGruposRoute
  '/respostas': typeof AppRespostasRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/fluxos/$flowId': typeof AppFluxosFlowIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/broadcasts': typeof AppBroadcastsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/conectar': typeof AppConectarRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/disparos': typeof AppDisparosRoute
  '/_app/fluxos': typeof AppFluxosRouteWithChildren
  '/_app/grupos': typeof AppGruposRoute
  '/_app/respostas': typeof AppRespostasRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/fluxos/$flowId': typeof AppFluxosFlowIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/broadcasts'
    | '/chat'
    | '/conectar'
    | '/config'
    | '/contatos'
    | '/disparos'
    | '/fluxos'
    | '/grupos'
    | '/respostas'
    | '/templates'
    | '/fluxos/$flowId'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/broadcasts'
    | '/chat'
    | '/conectar'
    | '/config'
    | '/contatos'
    | '/disparos'
    | '/fluxos'
    | '/grupos'
    | '/respostas'
    | '/templates'
    | '/'
    | '/fluxos/$flowId'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/broadcasts'
    | '/_app/chat'
    | '/_app/conectar'
    | '/_app/config'
    | '/_app/contatos'
    | '/_app/disparos'
    | '/_app/fluxos'
    | '/_app/grupos'
    | '/_app/respostas'
    | '/_app/templates'
    | '/_app/'
    | '/_app/fluxos/$flowId'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcasts': {
      id: '/_app/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AppBroadcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conectar': {
      id: '/_app/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof AppConectarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disparos': {
      id: '/_app/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof AppDisparosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxos': {
      id: '/_app/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof AppFluxosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos': {
      id: '/_app/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AppGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/respostas': {
      id: '/_app/respostas'
      path: '/respostas'
      fullPath: '/respostas'
      preLoaderRoute: typeof AppRespostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxos/$flowId': {
      id: '/_app/fluxos/$flowId'
      path: '/$flowId'
      fullPath: '/fluxos/$flowId'
      preLoaderRoute: typeof AppFluxosFlowIdRouteImport
      parentRoute: typeof AppFluxosRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFluxosRouteChildren {
  AppFluxosFlowIdRoute: typeof AppFluxosFlowIdRoute
}

const AppFluxosRouteChildren: AppFluxosRouteChildren = {
  AppFluxosFlowIdRoute: AppFluxosFlowIdRoute,
}

const AppFluxosRouteWithChildren = AppFluxosRoute._addFileChildren(
  AppFluxosRouteChildren,
)

interface AppRouteChildren {
  AppBroadcastsRoute: typeof AppBroadcastsRoute
  AppChatRoute: typeof AppChatRoute
  AppConectarRoute: typeof AppConectarRoute
  AppConfigRoute: typeof AppConfigRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDisparosRoute: typeof AppDisparosRoute
  AppFluxosRoute: typeof AppFluxosRouteWithChildren
  AppGruposRoute: typeof AppGruposRoute
  AppRespostasRoute: typeof AppRespostasRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBroadcastsRoute: AppBroadcastsRoute,
  AppChatRoute: AppChatRoute,
  AppConectarRoute: AppConectarRoute,
  AppConfigRoute: AppConfigRoute,
  AppContatosRoute: AppContatosRoute,
  AppDisparosRoute: AppDisparosRoute,
  AppFluxosRoute: AppFluxosRouteWithChildren,
  AppGruposRoute: AppGruposRoute,
  AppRespostasRoute: AppRespostasRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
